import { MAX_TIMER_DELAY_MS } from "./attempts.js";
export interface CommandCodeConfiguration { readonly conversion:{readonly request:{readonly syntheticMissingToolResultOutputType:"text"|"error-text"};readonly response:{readonly pauseTurn:"stop"|"error";readonly unknownEvent:"error"|"ignore"}};readonly request:{readonly transport:{readonly timeoutMs:number|null;readonly maxRetries:number;readonly maxRetryDelayMs:number}};readonly response:{readonly errorCapture:{readonly bodyReadTimeoutMs:number;readonly maxBodyBytes:number;readonly maxClientMessageChars:number}} }
const snapshots = new WeakSet<object>();
function record(v:unknown,p:string):Record<string,unknown>{if(typeof v!=="object"||v===null||Array.isArray(v))throw new Error(`${p} must be an object`);return v as Record<string,unknown>}
function keys(v:Record<string,unknown>,a:readonly string[],p:string):void{for(const k of Object.keys(v))if(!a.includes(k))throw new Error(`${p}.${k} is unknown`)}
function choice<T extends string>(v:unknown,d:T,a:readonly T[],p:string):T{if(v===undefined)return d;if(typeof v!=="string"||!a.includes(v as T))throw new Error(`${p} must be one of: ${a.join(", ")}`);return v as T}
function integer(v:unknown,d:number,min:number,max:number,p:string):number{if(v===undefined)return d;if(!Number.isSafeInteger(v)||(v as number)<min||(v as number)>max)throw new Error(`${p} must be a safe integer from ${min} to ${max}`);return v as number}
function optionalTimeout(v:unknown,p:string):number|null{if(v===undefined||v===null)return null;return integer(v,0,1,MAX_TIMER_DELAY_MS,p)}
export function parseCommandCodeConfiguration(value:unknown={},path='providerPackages["@luckytoken/provider-commandcode-private"]'):CommandCodeConfiguration{const root=record(value,path);keys(root,["conversion","request","response"],path);const conversion=record(root.conversion===undefined?{}:root.conversion,`${path}.conversion`);keys(conversion,["request","response"],`${path}.conversion`);const cr=record(conversion.request===undefined?{}:conversion.request,`${path}.conversion.request`);keys(cr,["syntheticMissingToolResultOutputType"],`${path}.conversion.request`);const cs=record(conversion.response===undefined?{}:conversion.response,`${path}.conversion.response`);keys(cs,["pauseTurn","unknownEvent"],`${path}.conversion.response`);const request=record(root.request===undefined?{}:root.request,`${path}.request`);keys(request,["transport"],`${path}.request`);const transport=record(request.transport===undefined?{}:request.transport,`${path}.request.transport`);keys(transport,["timeoutMs","maxRetries","maxRetryDelayMs"],`${path}.request.transport`);const response=record(root.response===undefined?{}:root.response,`${path}.response`);keys(response,["errorCapture"],`${path}.response`);const capture=record(response.errorCapture===undefined?{}:response.errorCapture,`${path}.response.errorCapture`);keys(capture,["bodyReadTimeoutMs","maxBodyBytes","maxClientMessageChars"],`${path}.response.errorCapture`);const snapshot=Object.freeze({conversion:Object.freeze({request:Object.freeze({syntheticMissingToolResultOutputType:choice(cr.syntheticMissingToolResultOutputType,"text",["text","error-text"],`${path}.conversion.request.syntheticMissingToolResultOutputType`)}),response:Object.freeze({pauseTurn:choice(cs.pauseTurn,"stop",["stop","error"],`${path}.conversion.response.pauseTurn`),unknownEvent:choice(cs.unknownEvent,"error",["error","ignore"],`${path}.conversion.response.unknownEvent`)})}),request:Object.freeze({transport:Object.freeze({timeoutMs:optionalTimeout(transport.timeoutMs,`${path}.request.transport.timeoutMs`),maxRetries:integer(transport.maxRetries,0,0,100,`${path}.request.transport.maxRetries`),maxRetryDelayMs:integer(transport.maxRetryDelayMs,60_000,0,MAX_TIMER_DELAY_MS,`${path}.request.transport.maxRetryDelayMs`)})}),response:Object.freeze({errorCapture:Object.freeze({bodyReadTimeoutMs:integer(capture.bodyReadTimeoutMs,5_000,1,MAX_TIMER_DELAY_MS,`${path}.response.errorCapture.bodyReadTimeoutMs`),maxBodyBytes:integer(capture.maxBodyBytes,65_536,1,16*1024*1024,`${path}.response.errorCapture.maxBodyBytes`),maxClientMessageChars:integer(capture.maxClientMessageChars,4_096,1,65_536,`${path}.response.errorCapture.maxClientMessageChars`)})})});snapshots.add(snapshot);return snapshot}
export function bindCommandCodeConfiguration(value:unknown):CommandCodeConfiguration{if(typeof value!=="object"||value===null||!snapshots.has(value))throw new Error("Provider Package configuration is not a CommandCode-owned snapshot");return value as CommandCodeConfiguration}
