// @ts-nocheck -- generated upstream JavaScript; signatures, dependencies and wire parity are certified.
/* eslint-disable */
// Generated by npm run pi:upgrade. Do not edit.
// Pi 1.0.0; source: node_modules/@earendil-works/pi-ai/dist/api/anthropic-messages.js; SHA256: a0644ab05cf7ee3e4d566f21113d5b6c2361588237c999a45fa0d7935b68af10
// Local modifications: Tools Context read replaced with boolean hasTools; federation branch omitted (not a certified Native credential path).
/*
MIT License
Copyright (c) 2025 Mario Zechner

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
import Anthropic from "@anthropic-ai/sdk";
import { getPiUserAgent } from "@earendil-works/pi-ai/utils/pi-user-agent";

const claudeCodeVersion = "2.1.280";

const FINE_GRAINED_TOOL_STREAMING_BETA = "fine-grained-tool-streaming-2025-05-14";

const INTERLEAVED_THINKING_BETA = "interleaved-thinking-2025-05-14";

const SERVER_SIDE_FALLBACK_BETA = "server-side-fallback-2026-07-01";

const MID_CONVERSATION_OUTPUT_CONFIG_BETA = "mid-conversation-output-config-2026-07-01";

const THINKING_BINDING_CONTROLS_BETA = "thinking-binding-controls-2026-08-01";

const MID_CONVERSATION_TOOL_CHANGES_BETA = "mid-conversation-tool-changes-2026-07-01";

function shouldUseServerSideFallbackBeta(model) {
    return (model.compat?.allowedFallbackModels?.length ?? 0) > 0;
}

function getAnthropicCompat(model) {
    const isOpenRouter = model.provider === "openrouter" || model.baseUrl.includes("openrouter.ai");
    return {
        supportsEagerToolInputStreaming: model.compat?.supportsEagerToolInputStreaming ?? true,
        supportsLongCacheRetention: model.compat?.supportsLongCacheRetention ?? true,
        sendSessionAffinityHeaders: model.compat?.sendSessionAffinityHeaders ?? isOpenRouter,
        sessionAffinityFormat: model.compat?.sessionAffinityFormat ?? (isOpenRouter ? "openrouter" : undefined),
        supportsCacheControlOnTools: model.compat?.supportsCacheControlOnTools ?? true,
        supportsTemperature: model.compat?.supportsTemperature ?? true,
        allowEmptySignature: model.compat?.allowEmptySignature ?? false,
        supportsStrictTools: model.compat?.supportsStrictTools ?? false,
        supportsMidConvoSystemMessages: model.compat?.supportsMidConvoSystemMessages ?? false,
        supportsMidConvoToolChanges: model.compat?.supportsMidConvoToolChanges ?? false,
    };
}

function mergeHeaders(...headerSources) {
    const merged = {};
    for (const headers of headerSources) {
        if (headers) {
            Object.assign(merged, headers);
        }
    }
    return merged;
}

function mergeClientHeaders(...headerSources) {
    return mergeHeaders({ "User-Agent": getPiUserAgent() }, ...headerSources);
}

class PiAnthropic extends Anthropic {
    _shouldResolveDefaultCredentials() {
        return false;
    }
}

function isOAuthToken(apiKey) {
    return apiKey.includes("sk-ant-oat");
}

function createClient(model, apiKey, optionsHeaders, fetch, dynamicHeaders, sessionId) {
    // Copilot: Bearer auth.
    if (model.provider === "github-copilot") {
        const client = new PiAnthropic({
            apiKey: null,
            authToken: apiKey ?? null,
            baseURL: model.baseUrl,
            dangerouslyAllowBrowser: true,
            fetch,
            defaultHeaders: mergeClientHeaders({
                accept: "application/json",
                "anthropic-dangerous-direct-browser-access": "true",
            }, model.headers, dynamicHeaders, optionsHeaders),
        });
        return { client, isOAuthToken: false };
    }
    // OAuth: Bearer auth, Claude Code identity headers
    if (apiKey && isOAuthToken(apiKey)) {
        const client = new PiAnthropic({
            apiKey: null,
            authToken: apiKey,
            baseURL: model.baseUrl,
            dangerouslyAllowBrowser: true,
            fetch,
            defaultHeaders: mergeClientHeaders({
                accept: "application/json",
                "anthropic-dangerous-direct-browser-access": "true",
                "user-agent": `claude-cli/${claudeCodeVersion}`,
                "x-app": "cli",
            }, model.headers, optionsHeaders),
        });
        return { client, isOAuthToken: true };
    }
    // API key, header-owned auth, or workload identity federation.
    const compat = getAnthropicCompat(model);
    const sessionAffinityHeaders = {};
    if (sessionId && compat.sendSessionAffinityHeaders) {
        const header = compat.sessionAffinityFormat === "openrouter" ? "x-session-id" : "x-session-affinity";
        sessionAffinityHeaders[header] = sessionId;
    }
    const defaultHeaders = mergeClientHeaders({
        accept: "application/json",
        "anthropic-dangerous-direct-browser-access": "true",
    }, sessionAffinityHeaders, model.headers, optionsHeaders);
    
    const client = new PiAnthropic({
        apiKey: apiKey ?? null,
        authToken: null,
        baseURL: model.baseUrl,
        dangerouslyAllowBrowser: true,
        fetch,
        defaultHeaders,
    });
    return { client, isOAuthToken: false };
}

function getBetaFeatures(model, hasTools, isOAuthToken, nativeToolChanges, options) {
    let configuredFeatures;
    for (const headers of [model.headers, options?.headers]) {
        for (const [name, value] of Object.entries(headers ?? {})) {
            if (name.toLowerCase() === "anthropic-beta")
                configuredFeatures = value;
        }
    }
    if (configuredFeatures === null)
        return [];
    if (configuredFeatures !== undefined) {
        return [
            ...new Set(configuredFeatures
                .split(",")
                .map((feature) => feature.trim())
                .filter((feature) => feature.length > 0)),
        ];
    }
    const features = [];
    if (isOAuthToken)
        features.push("claude-code-20250219", "oauth-2025-04-20");
    if (shouldUseFineGrainedToolStreamingBeta(model, hasTools))
        features.push(FINE_GRAINED_TOOL_STREAMING_BETA);
    if (model.reasoning &&
        options?.thinkingEnabled === true &&
        (options.interleavedThinking ?? true) &&
        model.compat?.forceAdaptiveThinking !== true) {
        features.push(INTERLEAVED_THINKING_BETA);
    }
    if (shouldUseServerSideFallbackBeta(model))
        features.push(SERVER_SIDE_FALLBACK_BETA);
    if (model.compat?.supportsMidConvoEffort === true) {
        features.push(MID_CONVERSATION_OUTPUT_CONFIG_BETA, THINKING_BINDING_CONTROLS_BETA);
    }
    if (nativeToolChanges)
        features.push(MID_CONVERSATION_TOOL_CHANGES_BETA);
    return [...new Set(features)];
}

function shouldUseFineGrainedToolStreamingBeta(model, hasTools) {
    return hasTools && !getAnthropicCompat(model).supportsEagerToolInputStreaming;
}

export { createClient, getBetaFeatures, getAnthropicCompat, claudeCodeVersion };
