import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";

import { CLAUDE_CODE_VERSION } from "../../src/provider-native-anthropic/envelope.js";

/**
 * Provider Native mirrors the envelope the pinned Pi runtime produces, and
 * with B2′ that envelope is generated by the vendor SDK. Token therefore has
 * to resolve the same vendor SDK version Pi declares — the previous
 * `@anthropic-ai/sdk` drift (Token kept 0.91.1 while Pi moved to 0.124.0) is
 * exactly the failure this gate exists to catch.
 *
 * The behavioural half of the guarantee lives in the Pi parity tests; this
 * gate fails fast with both version values when a Pi upgrade moves an SDK.
 */
const VENDOR_SDKS = ["openai", "@anthropic-ai/sdk"] as const;

interface PackageManifest {
  readonly version?: string;
  readonly dependencies?: Readonly<Record<string, string>>;
  readonly devDependencies?: Readonly<Record<string, string>>;
}

async function manifest(relativePath: string): Promise<PackageManifest> {
  return JSON.parse(
    await readFile(new URL(relativePath, import.meta.url), "utf8"),
  ) as PackageManifest;
}

describe("Provider Native vendor SDK identity gate", () => {
  it("declares the vendor SDK versions the pinned Pi runtime declares", async () => {
    const token = await manifest("../../package.json");
    const pi = await manifest("../../node_modules/@earendil-works/pi-ai/package.json");

    for (const name of VENDOR_SDKS) {
      const piVersion = pi.dependencies?.[name];
      expect(piVersion, `pinned Pi runtime must declare ${name}`).toBeDefined();
      expect(
        token.dependencies?.[name],
        `Token must depend on ${name}@${piVersion} to mirror Pi's envelope`,
      ).toBe(piVersion);
    }
  });

  it("resolves the declared vendor SDK versions from the repository root", async () => {
    const token = await manifest("../../package.json");

    for (const name of VENDOR_SDKS) {
      const declared = token.dependencies?.[name];
      const installed = await manifest(
        `../../node_modules/${name}/package.json`,
      );
      expect(
        installed.version,
        `installed ${name} must match the declared ${declared}`,
      ).toBe(declared);
    }
  });

  it("mirrors the Claude Code identity the pinned Pi Anthropic adapter pins", async () => {
    const adapter = await readFile(
      new URL(
        "../../node_modules/@earendil-works/pi-ai/dist/api/anthropic-messages.js",
        import.meta.url,
      ),
      "utf8",
    );
    const pinned = /const claudeCodeVersion = "([^"]+)"/u.exec(adapter)?.[1];
    expect(pinned, "pinned Pi adapter must declare claudeCodeVersion").toBeDefined();
    expect(
      CLAUDE_CODE_VERSION,
      "the OAuth Claude Code identity header must match the pinned Pi adapter",
    ).toBe(pinned);
  });
});
