export {
  controlPlaneVersion,
  assertControlPlaneEndpoint,
  type ApplicationCommand,
  type ApplicationCommandConflict,
  type ApplicationCommandConflictCode,
  type ApplicationCommandExecution,
  type ApplicationCommandHandler,
  type ApplicationCommandOutcome,
  type ApplicationCommandResult,
  type ApplicationCommandResultDeliveredHandler,
  type ApplicationIdentity,
  type ApplicationOwnership,
  type ApplicationStatus,
  type AutoStartRegistration,
  type CatalogCommand,
  type CatalogCommandHandler,
  type CatalogCommandOutcome,
  type CatalogCommandResult,
  type CatalogModelAvailability,
  type CatalogModelProjection,
  type CatalogProviderProjection,
  type CatalogProviderState,
  type CatalogRefreshErrorProjection,
  type CatalogRefreshReportProjection,
  type CatalogRefreshTrigger,
  type CatalogSnapshotProjection,
  type CatalogStatusProjection,
  type AgentIntegrationEffectProjection,
  type AgentIntegrationId,
  type AgentIntegrationObservedState,
  type AgentIntegrationOperationResult,
  type AgentIntegrationProjection,
  type AgentInjectionScope,
  type AgentIntegrationsCommand,
  type AgentIntegrationsCommandHandler,
  type AgentIntegrationsCommandResult,
  type AgentIntegrationsState,
  type ProviderSource,
  type AuthInfoLink,
  type AuthInteractionChannel,
  type AuthInteractionEvent,
  type AuthInteractionResponse,
  type AuthPromptOption,
  type ControlPlaneClient,
  type ControlPlaneDisconnect,
  type ControlPlaneEndpoint,
  type DataPlaneFailure,
  type DataPlaneFailureCode,
  type DataPlaneStatus,
  type EffectiveCatalogBaseline,
  type EffectiveCatalogCompositionError,
  type EffectiveCatalogProjection,
  type EffectiveModelCost,
  type EffectiveModelLayer,
  type EffectiveModelProjection,
  type EffectiveProviderLayer,
  type EffectiveProviderProjection,
  type HelloResult,
  type ModelsCommand,
  type ModelsCommandHandler,
  type ModelsCommandOutcome,
  type ModelsCommandResult,
  type ModelsFileError,
  type ModelsFileErrorKind,
  type ModelsFileErrorLocation,
  type ModelsFileState,
  type ModelsProjection,
  type PublicModelProjection,
  type PublicModelsCommand,
  type PublicModelsCommandHandler,
  type PublicModelsCommandOutcome,
  type PublicModelsCommandResult,
  type PublicModelsEndpointProjection,
  type PublicModelsState,
  type PublicProviderProjection,
  type RegisteredSetting,
  type RunningControlPlane,
  type RuntimeCommand,
  type RuntimeCommandConflict,
  type RuntimeCommandConflictCode,
  type RuntimeCommandExecution,
  type RuntimeCommandHandler,
  type RuntimeCommandOutcome,
  type RuntimeCommandResult,
  type RuntimeStatusPublisher,
  type SettingsCommand,
  type SettingsCommandHandler,
  type SettingsCommandOutcome,
  type SettingsCommandResult,
  type SettingsProjection,
  type StatusEvent,
  type StatusSnapshot,
} from "./contracts.js";
export type {
  CredentialProfileAuthType,
  CredentialProfileHealth,
  CredentialProfileOptionsProjection,
  CredentialProfileProjectionV1,
  CredentialProfilesCommand,
  CredentialProfilesCommandHandler,
  CredentialProfilesCommandOutcome,
  CredentialProfilesCommandResult,
  CredentialProfilesProjectionV1,
  ProviderCredentialAuthMethodProjection,
  ProviderCredentialOptionProjection,
  ProviderCredentialProfilesProjectionV1,
  ProviderProfileAuthCommand,
  ProviderProfileAuthCommandHandler,
  ProviderProfileAuthCommandOutcome,
  ProviderProfileAuthCommandResult,
} from "./credential-profiles-contract.js";
export {
  decodeCredentialProfilesCommand,
  decodeCredentialProfilesCommandResult,
  decodeProviderProfileAuthCommand,
  decodeProviderProfileAuthCommandResult,
} from "./wire-credential-profiles.js";
export type {
  AttentionCategory,
  AttentionCondition,
  AttentionPage,
  AttentionProjection,
  RecentRequestFailures,
} from "./contracts.js";
export { RECENT_REQUEST_FAILURE_WINDOW_MS } from "./contracts.js";
export { decodeAttentionProjection } from "./attention-contract.js";

export type {
  BackupCommand,
  BackupCommandHandler,
  BackupCreateCommand,
  BackupFailure,
  BackupFailureCode,
  BackupManifestEntrySummary,
  BackupManifestSummary,
  BackupManagementResult,
  BackupMode,
  BackupResult,
  CompatibilityIssue,
  RecoveryProjection,
  HistoryCommand,
  HistoryCommandHandler,
  HistoryCommandResult,
  HistoryCounts,
  HistoryDeleteCommand,
  HistoryDeleteFailure,
  HistoryDeletePreview,
  HistoryDeleteResult,
  HistoryDeleteManagementResult,
  HistoryExportCommand,
  HistoryExportFailure,
  HistoryExportFailureCode,
  HistoryExportManifestSummary,
  HistoryExportResult,
  HistoryExportManagementResult,
  HistoryQueryResult,
  HistoryQueryManagementResult,
  HistoryRange,
} from "./contracts.js";
export {
  decodeHistoryDeleteCommand,
  decodeHistoryDeleteResult,
  decodeHistoryDeleteManagementResult,
  decodeHistoryExportCommand,
  decodeHistoryExportResult,
  decodeHistoryExportManagementResult,
  decodeHistoryQueryResult,
  decodeHistoryQueryManagementResult,
  decodeHistoryRange,
} from "./wire-history.js";
export {
  decodeBackupCommand,
  decodeBackupResult,
  decodeBackupManagementResult,
  decodeRecoveryProjection,
} from "./wire-backup.js";
export { decodeAgentIntegrationsCommandResult } from "./wire.js";
export {
  ANALYTICS_CONTRACT_VERSION,
  MAX_ANALYTICS_DAY_SERIES_SPAN_MS,
  MAX_ANALYTICS_FILTER_VALUES,
  MAX_ANALYTICS_GROUPS,
  MAX_ANALYTICS_HOUR_SERIES_SPAN_MS,
  MAX_ANALYTICS_OPTIONS_VALUES,
  normalizeAnalyticsQuery,
  type AnalyticsBucket,
  type AnalyticsManagementResult,
  type AnalyticsFilter,
  type AnalyticsGroupBy,
  type AnalyticsGroupRow,
  type AnalyticsOptionsResult,
  type AnalyticsProfileOption,
  type AnalyticsQuery,
  type AnalyticsQueryHandler,
  type AnalyticsQueryResult,
  type AnalyticsResult,
  type AnalyticsSeriesGranularity,
  type AnalyticsSummary,
} from "./analytics-contract.js";
export {
  decodeAnalyticsResult,
  decodeAnalyticsManagementResult,
  decodeAnalyticsSummary,
} from "./wire-analytics.js";
export {
  nodePipeFallbackAccess,
  type PipeAccessRequirement,
  type PipeConnection,
  type PipeConnector,
  type PipeSecurityPolicy,
  type PipeServer,
  type PipeServerFactory,
  type PipeTransport,
} from "./pipe-transport.js";
export { createNodePipeTransport } from "./node-pipe-transport.js";
export {
  createLocalIpcAddress,
  type LocalIpcAddressOptions,
} from "./local-ipc-address.js";
export { parseControlPlaneDescriptor } from "./descriptor.js";

export { maxControlPlaneFrameBytes } from "./framing.js";

export {
  MAX_REQUEST_ARTIFACT_CHUNK_BYTES,
  MAX_REQUEST_DIAGNOSTICS_DETAIL_ITEMS,
  MAX_REQUEST_DIAGNOSTICS_QUERY_LIMIT,
  type ArtifactPersistedObservation,
  type AttemptObservedPersistedObservation,
  type ClientResponsePresentation,
  type ClientResponsePreparedPersistedObservation,
  type ConversionNoticePersistedObservation,
  type DataPlaneLane,
  type DiagnosticsReadResult,
  type DiagnosticsSubscription,
  type DiagnosticsUnavailableProjection,
  type DiagnosticsUnavailableResult,
  type FailureDetectedPersistedObservation,
  type HandoffPersistedObservation,
  type LaneCommittedPersistedObservation,
  type ModelResolvedPersistedObservation,
  type ProfileAttributedPersistedObservation,
  type RequestAnalyticsOutcome,
  type RequestArtifactDescriptor,
  type RequestArtifactChunkReadResult,
  type RequestArtifactGetInput,
  type RequestArtifactReadResult,
  type RequestArtifactState,
  type RequestCancellationSnapshot,
  type RequestHandoffOutcome,
  type RequestIdentityEstablishedPersistedObservation,
  type RequestIncident,
  type RequestJourneyDirection,
  type RequestJourneyDetailReadResult,
  type RequestJourneyGetInput,
  type RequestJourneyAdmission,
  type RequestJourneyLocation,
  type RequestJourneyOperation,
  type RequestJourneyOperationCandidate,
  type RequestJourneyOutcome,
  type RequestJourneyPhase,
  type RequestJourneyPersistedObservation,
  type RequestJourneyQuery,
  type RequestJourneyQueryReadResult,
  type RequestJourneyQueryResult,
  type RequestJourneyRecord,
  type RequestJourneySubject,
  type RequestJourneySummary,
  type RequestJourneyUsageSummary,
  type RequestJourneySubscriber,
  type RequestJourneySubscriptionEvent,
  type RequestJourneyTimelineEvent,
  type RequestWorkOutcome,
  type RuntimeEventQuery,
  type RuntimeEventQueryReadResult,
  type RuntimeEventQueryResult,
  type RuntimeEventRecord,
  type RuntimeEventSubscriber,
  type RuntimeEventSubscriptionEvent,
  type StepCompletedPersistedObservation,
  type StepEnteredPersistedObservation,
  type TerminalUsagePersistedObservation,
  type WorkOutcomeCommittedPersistedObservation,
  type UnifiedDiagnosticsManagement,
  type UnifiedDiagnosticsSubscriptionEvent,
} from "./request-diagnostics-contract.js";
export {
  decodeRequestArtifactChunkReadResult,
  decodeRequestArtifactGetInput,
  decodeRequestArtifactReadResult,
  decodeRequestJourneyDetailReadResult,
  decodeRequestJourneyGetInput,
  decodeRequestJourneyRecord,
  decodeRequestJourneyQuery,
  decodeRequestJourneyQueryResult,
  decodeRequestJourneyQueryReadResult,
  decodeRequestJourneySummary,
  decodeRuntimeEventQuery,
  decodeRuntimeEventQueryResult,
  decodeRuntimeEventQueryReadResult,
  decodeRuntimeEventRecord,
  decodeUnifiedDiagnosticsSubscriptionEvent,
} from "./wire-request-diagnostics.js";

import {
  connectApplicationControlPlane,
  type ControlPlaneClientDependencies,
} from "./client.js";
import {
  startApplicationStatusHost,
  type StartControlPlaneOptions,
} from "./application-status-host.js";

export type ControlPlaneDependencies = ControlPlaneClientDependencies;

export const connectControlPlane = connectApplicationControlPlane;
export const startControlPlane = startApplicationStatusHost;
export type { StartControlPlaneOptions };
