export {
  controlPlaneVersion,
  assertControlPlaneEndpoint,
  type ApplicationCommand,
  type ApplicationCommandConflict,
  type ApplicationCommandConflictCode,
  type ApplicationCommandExecution,
  type ApplicationCommandHandler,
  type ApplicationCommandOutcome,
  type ApplicationCommandResult,
  type ApplicationCommandResultDeliveredHandler,
  type ApplicationIdentity,
  type ApplicationOwnership,
  type ApplicationStatus,
  type AutoStartRegistration,
  type CatalogCommand,
  type CatalogCommandHandler,
  type CatalogCommandOutcome,
  type CatalogCommandResult,
  type CatalogModelAvailability,
  type CatalogModelProjection,
  type CatalogProviderProjection,
  type CatalogProviderState,
  type CatalogRefreshErrorProjection,
  type CatalogRefreshReportProjection,
  type CatalogRefreshTrigger,
  type CatalogSnapshotProjection,
  type CatalogStatusProjection,
  type AgentIntegrationEffectProjection,
  type AgentIntegrationId,
  type AgentIntegrationObservedState,
  type AgentIntegrationOperationResult,
  type AgentIntegrationProjection,
  type AgentInjectionScope,
  type AgentIntegrationsCommand,
  type AgentIntegrationsCommandHandler,
  type AgentIntegrationsCommandResult,
  type AgentIntegrationsState,
  type ProviderSource,
  type AuthInfoLink,
  type AuthInteractionChannel,
  type AuthInteractionEvent,
  type AuthInteractionResponse,
  type AuthPromptOption,
  type ControlPlaneDiagnostics,
  type ControlPlaneClient,
  type ControlPlaneDisconnect,
  type ControlPlaneEndpoint,
  type ControlPlaneRequestLedger,
  type CaptureDraft,
  type CaptureEvent,
  type CaptureEventFact,
  type CaptureFailureDraft,
  type CapturePersistedState,
  type CaptureQuery,
  type CaptureQueryResult,
  type CaptureRangeQuery,
  type CaptureRangeQueryResult,
  type CaptureRecord,
  type CaptureState,
  type CaptureTimingEntry,
  type CaptureWriteFailure,
  type ControlPlaneCapture,
  type DeepCaptureStore,
  type DeepCaptureStoreFactory,
  type DataPlaneFailure,
  type DataPlaneFailureCode,
  type DataPlaneStatus,
  type EffectiveCatalogBaseline,
  type EffectiveCatalogCompositionError,
  type EffectiveCatalogProjection,
  type EffectiveModelCost,
  type EffectiveModelLayer,
  type EffectiveModelProjection,
  type EffectiveProviderLayer,
  type EffectiveProviderProjection,
  type HelloResult,
  type LedgerAliasFact,
  type LedgerAttempt,
  type LedgerCredentialAttempt,
  type LedgerCredentialCapture,
  type LedgerCredentialUsage,
  type LedgerAuthFacts,
  type LedgerFailureInput,
  type LedgerFailureSummary,
  type LedgerFacts,
  type LedgerModelSnapshot,
  type LedgerNotice,
  type LedgerOutcome,
  type LedgerPersistenceFailure,
  type LedgerPhase,
  type LedgerTerminalFacts,
  type LedgerTerminalOutcome,
  type ModelsCommand,
  type ModelsCommandHandler,
  type ModelsCommandOutcome,
  type ModelsCommandResult,
  type ModelsFileError,
  type ModelsFileErrorKind,
  type ModelsFileErrorLocation,
  type ModelsFileState,
  type ModelsProjection,
  type PrimaryStatus,
  type PublicModelProjection,
  type PublicModelsCommand,
  type PublicModelsCommandHandler,
  type PublicModelsCommandOutcome,
  type PublicModelsCommandResult,
  type PublicModelsEndpointProjection,
  type PublicModelsState,
  type PublicProviderProjection,
  type RegisteredSetting,
  type RequestLedger,
  type RequestLedgerDetailProjection,
  type RequestLedgerEntry,
  type RequestLedgerEvent,
  type RequestLedgerListProjection,
  type RequestLedgerQuery,
  type RequestLedgerQueryResult,
  type RequestLedgerRecord,
  type RequestLedgerStore,
  type RequestLedgerStoreFactory,
  type RequestUsageProjection,
  type RunningControlPlane,
  type RuntimeCommand,
  type RuntimeCommandConflict,
  type RuntimeCommandConflictCode,
  type RuntimeCommandExecution,
  type RuntimeCommandHandler,
  type RuntimeCommandOutcome,
  type RuntimeCommandResult,
  type RuntimeStatusPublisher,
  type SettingsCommand,
  type SettingsCommandHandler,
  type SettingsCommandOutcome,
  type SettingsCommandResult,
  type SettingsProjection,
  type StatusEvent,
  type StatusSnapshot,
  type RuntimeDiagnosticDraft,
  type RuntimeDiagnosticEvent,
  type RuntimeDiagnosticLevel,
  type RuntimeDiagnosticMessage,
  type RuntimeDiagnosticQuery,
  type RuntimeDiagnosticRecord,
  type RuntimeDiagnosticsQueryResult,
  type RuntimeDiagnosticsStore,
  type RuntimeDiagnosticsStoreFactory,
} from "./contracts.js";
export type {
  CredentialProfileAuthType,
  CredentialProfileHealth,
  CredentialProfileOptionsProjection,
  CredentialProfileProjectionV1,
  CredentialProfilesCommand,
  CredentialProfilesCommandHandler,
  CredentialProfilesCommandOutcome,
  CredentialProfilesCommandResult,
  CredentialProfilesProjectionV1,
  ProviderCredentialAuthMethodProjection,
  ProviderCredentialOptionProjection,
  ProviderCredentialProfilesProjectionV1,
  ProviderProfileAuthCommand,
  ProviderProfileAuthCommandHandler,
  ProviderProfileAuthCommandOutcome,
  ProviderProfileAuthCommandResult,
} from "./credential-profiles-contract.js";
export {
  decodeCredentialProfilesCommand,
  decodeCredentialProfilesCommandResult,
  decodeProviderProfileAuthCommand,
  decodeProviderProfileAuthCommandResult,
} from "./wire-credential-profiles.js";
export type {
  AttentionCategory,
  AttentionCondition,
  AttentionPage,
  AttentionProjection,
  RecentRequestFailures,
} from "./contracts.js";
export { RECENT_REQUEST_FAILURE_WINDOW_MS } from "./contracts.js";
export { decodeAttentionProjection } from "./attention-contract.js";

export type {
  BackupCommand,
  BackupCommandHandler,
  BackupCreateCommand,
  BackupFailure,
  BackupFailureCode,
  BackupManifestEntrySummary,
  BackupManifestSummary,
  BackupMode,
  BackupResult,
  CompatibilityIssue,
  RecoveryProjection,
  HistoryAcknowledgeResult,
  HistoryCommand,
  HistoryCommandHandler,
  HistoryCommandResult,
  HistoryCounts,
  HistoryDeleteAuthorityFailure,
  HistoryDeleteCommand,
  HistoryDeleteFailureCode,
  HistoryDeleteOutcome,
  HistoryDeletePreview,
  HistoryDeleteResult,
  HistoryExportCaptureMode,
  HistoryExportCommand,
  HistoryExportFailure,
  HistoryExportFailureCode,
  HistoryExportManifestSummary,
  HistoryExportOutcome,
  HistoryExportResult,
  HistoryQueryResult,
  HistoryRange,
  PersistenceAuthorityId,
  PersistenceAuthorityProjection,
  PersistenceProjection,
} from "./contracts.js";
export { PERSISTENCE_AUTHORITY_IDS } from "./contracts.js";
export {
  decodeHistoryDeleteCommand,
  decodeHistoryDeleteResult,
  decodeHistoryExportCommand,
  decodeHistoryExportResult,
  decodeHistoryQueryResult,
  decodeHistoryRange,
  decodePersistenceProjection,
} from "./wire-history.js";
export {
  decodeBackupCommand,
  decodeBackupResult,
  decodeRecoveryProjection,
} from "./wire-backup.js";
export {
  averageOutputSpeedUnavailableReason,
  deriveRequestStatus,
  formatDuration,
  formatPercent,
  formatTimestamp,
  formatTokenCount,
  formatTokensPerSecond,
  formatCacheHitRate,
  ledgerPhaseLabel,
  projectAverageOutputTokensPerSecond,
  projectRequestLedger,
  projectRequestLedgerDetail,
  projectRequestUsage,
  protocolDisplayName,
} from "./contracts.js";
export { decodeRequestLedgerEvent, decodeRequestLedgerQuery, decodeRequestLedgerRecord, decodeRequestLedgerResult } from "./wire-ledger.js";
export { decodeAgentIntegrationsCommandResult } from "./wire.js";
export { decodeCaptureEvent, decodeCaptureQuery, decodeCaptureQueryResult, decodeCaptureRecord } from "./wire-capture.js";
export {
  LEDGER_OUTCOMES,
  LEDGER_PHASES,
  assertLedgerOutcome,
  assertLedgerPhase,
} from "./contracts.js";
export {
  CAPTURE_STATES,
  assertCaptureState,
} from "./contracts.js";
export {
  RUNTIME_DIAGNOSTIC_LEVELS,
  RUNTIME_DIAGNOSTIC_SEVERITY,
  assertRuntimeDiagnosticLevel,
  severityAtLeast,
  normalizeDiagnosticQuery,
} from "./diagnostics-contract.js";
export {
  ANALYTICS_CONTRACT_VERSION,
  MAX_ANALYTICS_DAY_SERIES_SPAN_MS,
  MAX_ANALYTICS_FILTER_VALUES,
  MAX_ANALYTICS_GROUPS,
  MAX_ANALYTICS_HOUR_SERIES_SPAN_MS,
  MAX_ANALYTICS_OPTIONS_VALUES,
  normalizeAnalyticsQuery,
  type AnalyticsBucket,
  type AnalyticsFilter,
  type AnalyticsGroupBy,
  type AnalyticsGroupRow,
  type AnalyticsOptionsResult,
  type AnalyticsQuery,
  type AnalyticsQueryHandler,
  type AnalyticsQueryResult,
  type AnalyticsResult,
  type AnalyticsSeriesGranularity,
  type AnalyticsSummary,
} from "./analytics-contract.js";
export {
  decodeAnalyticsResult,
  decodeAnalyticsSummary,
} from "./wire-analytics.js";
export {
  nodePipeFallbackAccess,
  type PipeAccessRequirement,
  type PipeConnection,
  type PipeConnector,
  type PipeSecurityPolicy,
  type PipeServer,
  type PipeServerFactory,
  type PipeTransport,
} from "./pipe-transport.js";
export { createNodePipeTransport } from "./node-pipe-transport.js";
export {
  createLocalIpcAddress,
  type LocalIpcAddressOptions,
} from "./local-ipc-address.js";
export { parseControlPlaneDescriptor } from "./descriptor.js";

export { maxControlPlaneFrameBytes } from "./framing.js";

import {
  connectApplicationControlPlane,
  type ControlPlaneClientDependencies,
} from "./client.js";
import {
  startApplicationStatusHost,
  type StartControlPlaneOptions,
} from "./application-status-host.js";

export type ControlPlaneDependencies = ControlPlaneClientDependencies;

export const connectControlPlane = connectApplicationControlPlane;
export const startControlPlane = startApplicationStatusHost;
export type { StartControlPlaneOptions };
